language: php

addons:
    firefox: latest

cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

env:
    global:
        - PHPUNIT_FLAGS="-v --testdox"
        - PHPUNIT_FLAGS_UNIT_TESTS_ONLY="-v --testdox --configuration phpunit_unit_tests_only.xml.dist"
        - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
        - SYMFONY_DEPRECATIONS_HELPER="max[total]=999999&max[direct]=0"
        - FUNCTIONAL_TESTS_DEPENDENCIES="symfony/browser-kit:^5 symfony/css-selector:^5 symfony/framework-bundle:^5 symfony/twig-bundle:^5 symfony/panther:^1"

jobs:
    fast_finish: true
    include:
          # Test the latest stable release
        - php: 7.4
          env: STABILITY="stable" XDEBUG_MODE=coverage COVERAGE=true PHPUNIT_FLAGS="${PHPUNIT_FLAGS_UNIT_TESTS_ONLY} --coverage-text --coverage-clover=build/coverage.xml"  DEPENDENCIES="symfony/http-client:^5" SYMFONY_REQUIRE="5.4.*"
        - php: 8.0
          env: STABILITY="stable" XDEBUG_MODE=coverage COVERAGE=true PHPUNIT_FLAGS="${PHPUNIT_FLAGS_UNIT_TESTS_ONLY} --coverage-text --coverage-clover=build/coverage.xml"  DEPENDENCIES="symfony/http-client:^5" SYMFONY_REQUIRE="5.4.*"

          # Functional tests are only available for Symfony 5+
        - php: 7.4
          env: STABILITY="stable" PHPUNIT_FLAGS="${PHPUNIT_FLAGS_UNIT_TESTS_ONLY}" DEPENDENCIES="guzzlehttp/guzzle:^7" SYMFONY_REQUIRE="3.4.*"
        - php: 7.4
          env: STABILITY="stable" PHPUNIT_FLAGS="${PHPUNIT_FLAGS_UNIT_TESTS_ONLY}" DEPENDENCIES="symfony/http-client:^4" SYMFONY_REQUIRE="4.4.*"
        - php: 7.4
          env: STABILITY="stable" DEPENDENCIES="symfony/http-client:^5 ${FUNCTIONAL_TESTS_DEPENDENCIES}" SYMFONY_REQUIRE="5.4.*"

    allow_failures:
      # Latest commit to master
        - php: 7.2
          env: STABILITY="dev" DEPENDENCIES="symfony/http-client:^5 ${FUNCTIONAL_TESTS_DEPENDENCIES}" SYMFONY_REQUIRE="5.4.*"
        - php: 7.4
          env: STABILITY="dev" DEPENDENCIES="symfony/http-client:^5 ${FUNCTIONAL_TESTS_DEPENDENCIES}" SYMFONY_REQUIRE="5.4.*"
        - php: 8.0
          env: STABILITY="dev" DEPENDENCIES="symfony/http-client:^5 ${FUNCTIONAL_TESTS_DEPENDENCIES}" SYMFONY_REQUIRE="5.4.*"

before_install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.29.0-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - composer global require symfony/flex
    - composer require --no-update ${DEPENDENCIES}

install:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - ./vendor/bin/simple-phpunit install

script:
    - composer validate --strict --no-check-lock
    - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS
